var listk = [
"KTZ",
"Kaelen",
"Kai Kühne",
"Kanye West",
"Karen Walker",
"Karl Lagerfeld",
"Karolina Zmarlak",
"Kate Spade",
"Katie Ermilio",
"Katie Gallagher",
"Katy Rodriguez",
"Kaufman Franco",
"Kelly Wearstler",
"Kenneth Cole",
"Kenneth Pool",
"Kenzo",
"Kevork Kiledjian",
"Kimberly Ovitz",
"Kinder Aggugini",
"Koche",
"Koi Suwannagate",
"Kolor",
"Kris Van Assche",
"Krystof Strozyna",
"kanye west adidas originals",
"kls kimora lee simmons",
"",
"K.Spin(12)",
"k3&co(40)",
"Kahiko(1695)",
"kakatoo(92)",
"Kanana Project(182)",
"KANGOL(83)",
"Kaon(8)",
"KAREN WALKER(4)",
"KARHU(6)",
"KARINE(81)",
"Karrimor(4)",
"Kastane(281)",
"kate spade new york(466)",
"KATHARINE HAMNETT ladies(155)",
"KATHARINE HAMNETT LONDON (165)",
"KATHARINE ROSS(499)",
"Katie(149)",
"KATO`(5)",
"KATSUYUKI KODAMA(25)",
"KAVU(70)",
"KBF(847)",
"Keds(94)",
"KEEN(236)",
"Keikiii(49)",
"KEITA MARUYAMA(174)",
"Keith Haring(119)",
"Kengo Kuma + MA,YU (31)",
"KENZO(172)",
"ketty(293)",
"KHADI & CO(12)",
"Khaju(952)",
"khall designs(28)",
"KHRIO (6)",
"KicKers(35)",
"KID BLUE(893)",
"Kidole.(2)",
"KIDS LOVE GAITE(1)",
"KIFFE(3)",
"KIIRA(43)",
"Kiitos(1)",
"KIKKA THE DIARY OF(27)",
"KIKKER LAND(25)",
"kinetics(31)",
"Kinfolk(2)",
"kiryuyrik(41)",
"Kitica(66)",
"KITSUNE(28)",
"Kiwanda(19)",
"kladskap(1)",
"KLATTERMUSEN(29)",
"KLAUS HAAPANIEMI(107)",
"Klean Kanteen(58)",
"KLETTERWERKS(59)",
"knitchy(115)",
"knock through abstraction(119)",
"Kocochi(17)",
"kodomoe(1)",
"KOE(1040)",
"kolor / BEACON(1)",
"KotoDaMA(12)",
"KRAFTRIPS＆Co.(2)",
"KRIFF MAYER(157)",
"KRIS VAN ASSCHE(2)",
"KTZ(2)",
"ku:nel(1)",
"Kukka Lucca(34)",
"KUPU－KUPU(14)",
"kvell(39)",
]