var list = [
"ANREALAGE",
"And Re Walker",
"Andrew Gn",
"Angel Sanchez",
"Angelos Bratis",
"Ann Demeulemeester",
"Ann-Sofie Back Atelje",
"Anna Maier",
"Anna Molinari",
"Anna Sui",
"Anne Klein",
"Anne Valérie Hash",
"Anthony Vaccarello",
"Antonio Berardi",
"Antonio Marras",
"Anya Hindmarch",
"Apiece Apart",
"Aquascutum",
"Aquilano.Rimondi",
"Araks",
"Armand Basi",
"Armani Privé",
"Arthur Arbesser",
"Ashish",
"Ashley Williams",
"Assembly",
"Austin Scarlett",
"Awake",
"Azzaro",
"alexander lewis",
"area",
"atm Anthony thomas melillo",
"au jour le jour",
"A Bathing Ape",
"A Détacher",
"A MON GOUT",
"A STORE",
"A VONTADE",
"A.F. Vandevorst",
"A.D.S.R.",
"A.L.C.",
"A.P.C.",
"A.S.M",
"A.T",
"A・I・C",
"AAA",
"AAA+",
"Abaeté",
"ABAHOUSE",
"Abcdevol",
"Ability",
"ABYSS&HABIDECOR",
"Accessorize",
"Ace&Jig",
"ACME FURNITURE",
"ACNE",
"Acne Studios",
"ACRONYM",
"Actuel",
"ACUNEO",
"adabat",
"Adam",
"Adam clliford",
"ADAM ET ROPE'",
"Adam et Rope' Le Magasin",
"Adam Lippes",
"ADAM PATEK",
"Adam Selman",
"Adeam",
"ADER",
"Adidas",
"adidas by Raf Simons",
"Adidas by Stella McCartney",
"adidas originals",
"adidas Originals by 84-LAB.",
"adidas Originals by Jeremy Scott",
"ADIEU",
"ADIEU TRISTESSE",
"ADIEU TRISTESSE l'ecume des jours",
"ADIEU TRISTESSE LOISIR",
"aditional",
"Admiral",
"adonis green",
"ADPOSION",
"Afternoon Tea",
"AG",
"AG by aquagirl",
"Aganovich",
"agete",
"agete CLASSIC",
"agete FIRST",
"agete FOR MEN",
"AGNELLE",
"agnes b.",
"Agnona",
"AGNOST",
"ah",
"AHCAHCUM.muchacha",
"AHKAH",
"AHUM",
"AIGLE",
"aimer le mieux",
"Airpapel",
"Ajew",
"AKIRA NAKA",
"AKM",
"Akris",
"AL e RO design",
"Alabama Chanin",
"Alberta Ferretti",
"Albino",
"alcali",
"ALDIES",
"Aleanto",
"Alessandra Rich",
"Alessandro Dell Acqua",
"Alexander McQueen",
"Alexander Wang",
"Alexandre Herchcovitch",
"Alexandre Plokhov",
"Alexandre Vauthier",
"ALEXANDER YAMAGUCHI ",
"AlexanderLeeChang",
"Alexis Mabille",
"alfredoBANNISTER LADY`S",
"ALIAS",
"Alice + Olivia",
"Alice Roi",
"alima PURE",
"Alive Athletics",
"ALL BLACK",
"ALL ORDINARIES",
"ALLEGE",
"Allegra Hicks",
"Alluge",
"allureville",
"ALPHA",
"ALPHA CUBIC",
"Altuzarra",
"amabro",
"AMACA",
"AMBUSH",
"amelier MAJESTIC LEGON",
"Ameri",
"AMERICAN RAG CIE",
"AMERICANA",
"amie by miely",
"amijed",
"AMIMOC",
"AMINA COLLECTION",
"AMIW",
"amok",
"AMO'S STYLE by Triumph",
"amp japan",
"amp.",
"Ampersand",
"AMPHI(",
"Amplis",
"Amsale",
"An+u",
"analog lighting",
"anan",
"ANAP",
"ANAP GｉRL",
"ANAP HOME",
"ANAP kids",
"ANAP MEN",
"anap mimpi",
"ANAP School",
"anatelier",
"ANCHOR",
"and it_",
"and wander",
"Andemiu",
"Andersen-Andersen",
"andGIRL",
"ANDREA POMPILIO",
"ANDSUNS",
"Andy Warhol",
"AneCan",
"ANGEL HEART",
"Angler's House",
"ANGLOBAL SHOP",
"Anisha",
"Ank Rouge",
"Anna Marie",
"ANONYM CRAFTSMAN DESIGN",
"ANOTHER BRANCH",
"Another Edition",
"Anoutcommune",
"ANREALAGE",
"ANTHOLOGIE&CO.",
"ANTIHERO",
"ANTIPODIUM",
"any Fam",
"any SiS",
"ANYWHERE CHAIR",
"AOZORA",
"apart by lowrys",
"APPLEBUM",
"April77",
"Apuweiser-riche",
"AQUA SAVON",
"aquagirl",
"aquagirl shoes",
"aquvii",
"ar",
"archives",
"arenot",
"ARGITAL",
"Arnold Palmer",
"AROMEDICA",
"Arpege",
"arrive paris",
"arth",
"ARTS & CRAFTS",
"AS as know as",
"AS KNOW AS de base",
"AS KNOW AS PINKY",
"as time goes by",
"AS2OV",
"ASH",
"ASH STUDIO PARIS",
"ASICS",
"ASICS TIGER",
"ASPLUND",
"ASTORIA ODIER",
"ASYLUM",
"ASZAKKA",
"AT2",
"Atease",
"athe",
"Athena New York",
"Atlantic STARS",
"atmos",
"atmos girls",
"atmos/atmos girls",
"ato",
"ATSURO TAYAMA",
"attack the mind 7",
"attagirl",
"audrey and john wad",
"AULA",
"AULA AILA",
"AULI",
"Aunt Marie's",
"Auntie Rosa",
"AURALEE(16)",
"AURORA GRAN(79)",
"Avan Lily(595)",
"avie(271)",
"AVIREX(1567)",
"AVIREX Belle SELECT(31)",
"AXEL ROSE(7)",
"axes femme(1054)",
"Aymmy in the batty girls(424)",
"AZUL by moussy(3933)",
"AZUL ENCANTO(887)",
]
