var listb = [


"BAJA EAST",
"BCBG Max Azria",
"BLK DNM",
"BROCK COLLECTION",
"Badgley Mischka",
"Balenciaga",
"Bally",
"Balmain",
"Banana Republic",
"Band of Outsiders",
"Barbara",
"Barbara Bui",
"Barbara Casasola",
"Barbara Tfank",
"Basso & Brooke",
"Bebe",
"Behnaz Sarafpour",
"Belstaff",
"Benjamin Cho",
"Bensoni",
"Betsey Johnson",
"Betty Jackson",
"Biba",
"Bibhu Mohapatra",
"Bill Blass",
"Billy Reid",
"Blanc De Chine",
"Blumarine",
"Bottega Veneta",
"Bouchra Jarrar",
"Boudicca",
"Boy and Girl by Band of Outsiders",
"Brandon Maxwell",
"Brandon Sun",
"Brian Reyes",
"Brioni",
"Brood",
"Bruce",
"Brunello Cucinelli",
"Bruno Pieters",
"Burberry Prorsum",
"babyghost",
"",
"B ability(20)",
"B DONNA(137)",
"B.I.D.(342)",
"b.u.(10)",
"B:MING LIFE STORE by BEAMS(1250)",
"B'2nd re'qua(90)",
"b4BRONTIBAYPARIS(14)",
"baby ampersand(3)",
"BABY PURE(81)",
"BABYLONE(639)",
"bach(4)",
"Back Channel(19)",
"Badhiya(17)",
"BAG selection ONWARD(64)",
"BAL(23)",
"Balancoire(147)",
"Balcony and Bed(248)",
"BALLON(95)",
"BALMAIN(2)",
"banal chic bizarre(100)",
"Band of Outsiders(10)",
"Banner Barrett(619)",
"Barbarian(4)",
"Barbie(45)",
"Barbour(22)",
"BAREFOOT DREAMS(155)",
"BARK TANNAGE(29)",
"BARNYARDSTORM(517)",
"BARONS PAPILLOM(9)",
"BASECONTROL(123)",
"BASErange(3)",
"BATHCRAFT(34)",
"BATHROOM(28)",
"Battenwear(2)",
"BAUM UND PFERDGARTEN(5)",
"Baxter of California(14)",
"BAYFLOW(1263)",
"BE RADIANCE(66)",
"BE@RBRICK(14)",
"BEACH FEET(25)",
"BEAMS(76)",
"BEAMS BOY(1168)",
"BEAMS F(32)",
"BEAMS GOLF(421)",
"BEAMS LIGHTS Men's(54)",
"BEAMS LIGHTS Women's(1180)",
"BEAMS PLUS(1)",
"BEAMS T(199)",
"bea's up(1)",
"beats. by dr.dre(1)",
"BEAU COOPS(3)",
"Beaumont ORGANIC(26)",
"Beaure(45)",
"Beau're(244)",
"BEAU'RE SECOND(18)",
"beautiful people(25)",
"BEAUTY&YOUTH UNITED ARROWS(3574)",
"BEAVER(461)",
"BEAVER ORIGINAL(6)",
"BED J.W. FORD(1)",
"BED&BREAKFAST(281)",
"bedsidedrama(90)",
"BEEN TRILL(31)",
"BELIEVEINMIRACLE(17)",
"BELL FLORRIE (85)",
"BELLA FREUD(10)",
"BEN DAVIS(66)",
"BEN DAVIS ORIGINALS(86)",
"BEN DAVIS/PROJECT LINE(109)",
"benah(2)",
"BENETTON (UNITED COLORS OF BENETTON)(848)",
"BERGE(9)",
"BERNHARD WILLHELM(54)",
"Bertini(8)",
"beruf baggage(428)",
"BEST PACKING STORE(23)",
"BETONES(17)",
"BETTY CLUB(161)",
"BIANCA EPOCA(383)",
"Bianca`s closet(45)",
"Bibi Gramaglia(5)",
"BIJOU PIKO(241)",
"Bi-jouterie(3)",
"Bilitis dix-sept ans(86)",
"BILL WALL LEATHER(84)",
"BILLABONG(102)",
"BILLIONAIRE BOYS CLUB(111)",
"Binoche(12)",
"Biorista Organics(4)",
"BIRGITTE HERSKIND(5)",
"BIRKENSTOCK(291)",
"Bisue Ballerinas(3)",
"Bitter Ender(38)",
"Bitter Line(3)",
"BLACK BY MOUSSY(362)",
"BLACK by VANQUISH(4)",
"BLACK FLYS(5)",
"BLACK STAR & THE VELVET BORNS(10)",
"BLACKBARRETT by NEIL BARRETT(18)",
"blanc basque(68)",
"blAnks(6)",
"BLDK(1)",
"BLEU FORET(25)",
"BLISS POINT(1469)",
"blondy(86)",
"BLONDY ReLISH(705)",
"BLUE CHIP(21)",
"BLUE TORNADO(2)",
"bodco(167)",
"BOEMOS(9)",
"BOHEMIANS(69)",
"Boisson Chocolat(581)",
"BONAPETIT(6)",
"BONICA DOT(281)",
"BONICA dot GARDEN(200)",
"Bonjour Girl(4)",
"bonjour records(917)",
"BONNIE SPRINGS(11)",
"BONTRE(94)",
"BOOFOOWOO(140)",
"boreas(10)",
"BORNY(397)",
"BOSCH(397)",
"botocollax(5)",
"Bou Jeloud(1540)",
"BOUNTY HUNTER(40)",
"BOY LONDON(3)",
"bpr BEAMS(1920)",
"BRANIFF(7)",
"BRAUN(2)",
"BREE(192)",
"BRICS(3)",
"BRIEFING(98)",
"BRILLA per il gusto(6)",
"BRIM BRIM(20)",
"BRITISH GREEN(50)",
"BRIXTON(9)",
"Broderie & Co(75)",
"BRONTIBAYPARIS(67)",
"BROOKS(127)",
"BROOKS BROTHERS(161)",
"BROOKS HERITAGE(23)",
"BROSKI&SUPPLY(22)",
"BrownBrown(41)",
"BRTH BREATH(45)",
"BRUNO(214)",
"Bshop(123)",
"buddy(4)",
"BUILT NY(6)",
"bulle de savon(253)",
"BULSARA(28)",
"BURKS BULL(21)",
"Burner(41)",
"BURTON(81)",
"Butler Verner Sails(415)",
"BUTTERO(65)",
"BWGH for PUMA(34)",
"by boe(24)",
"by loveit(1)",
"byあしながおじさん(64)",
"B印 YOSHIDA(BEAMS×PORTER)(74)",
]
