var listc = [
"C-Neeon",
"CAMILLA AND MARC",
"CG",
"COPERNI FEMME",
"Cacharel",
"Calla",
"Calvin Klein Collection",
"Carlos Miele",
"Carmen Marc Valvo",
"Carolina Herrera",
"Carven",
"Catherine Malandrino",
"Cedric Charlier",
"Central Saint Martins",
"Chado Ralph Rucci",
"Chadwick Bell",
"Chaiken",
"Chanel",
"Charles Anastase",
"Charles Nolan",
"Charlotte Ronson",
"Chloe Sevigny for Opening Ceremony",
"ChloÃ« Sevigny for O.C.",
"Chloé",
"Chloë Sevigny for O.C.",
"Chris Benz",
"Christian Cota",
"Christian Dior",
"Christian Lacroix",
"Christian Siriano",
"Christian Wijnants",
"Christophe Lemaire",
"Christopher Kane",
"Christopher Raeburn",
"Christos",
"Claire Pettibone",
"Clements Ribeiro",
"Clover Canyon",
"Co",
"Coach",
"Collette Dinnigan",
"Comme des Garcons Comme des Garcons",
"Comme des Garçons",
"Commuun",
"Comptoir des Cotonniers",
"Costello Tagliapietra",
"Costume National",
"County of Milan",
"Courreges",
"Creatures of Comfort",
"Creatures of the Wind",
"Cushnie Et Ochs",
"Custo Barcelona",
"Cynthia Rowley",
"Cynthia Steffe",
"",
"C.E(3)",
"C.E.L.STORE(218)",
"C.I.L.(3)",
"C6(64)",
"CA4LA(5)",
"CABALLERO(30)",
"CABANE de ZUCCa(58)",
"CABBAGES & ROSES(93)",
"CABLOCAMURIE　(67)",
"cache cache(667)",
"cachenez(50)",
"Caie(1)",
"cal(121)",
"CAL O LINE(6)",
"Callipigia(49)",
"Calvin Klein(191)",
"CAMBIO(38)",
"CAMINANDO(4)",
"CAMPER(466)",
"CANADA GOOSE(43)",
"CANAL JEAN(118)",
"canal4℃(323)",
"CanCam(1)",
"Candy Stripper(146)",
"CANNABIS LADIES(47)",
"Canyon de chelly(1)",
"Capelli(25)",
"caph(216)",
"Caravana by A・I・C(126)",
"CAREER LINK(12)",
"Carhartt(84)",
"Carletti(48)",
"Carlie e felice(151)",
"carnelian(245)",
"CAROLINA GLASER(92)",
"CARRAIG DONN(2)",
"CARRANO(29)",
"CARRYNEST(1)",
"CARVEN(79)",
"CASEPLAY(1)",
"CASIO(152)",
"CASPER JOHN(243)",
"Casselini(145)",
"Castaner(3)",
"Cater-pillar(64)",
"Cath Kidston(183)",
"cava cava(194)",
"CECIL McBEE(454)",
"CEDRIC CHARLIER(1)",
"CeLL(54)",
"Chaco(4)",
"CHALAYAN(35)",
"chambre de charme(195)",
"Champion(341)",
"CHAN LUU(317)",
"Chang Mee(23)",
"chapter world(1415)",
"CHAPTER WORLD PREMIUM(7)",
"CHAPTER WORLD select (1177)",
"Charles & Keith (348)",
"CHEAP MONDAY(190)",
"cheek(465)",
"Cher(13)",
"CHIE MIHARA(5)",
"CHILD WOMAN(141)",
"chillax(14)",
"Chille anap(1325)",
"CHIME(148)",
"chinti and parker(1)",
"Chippewa(5)",
"Chloe(3)",
"Chloris(83)",
"CHOKiCHOKi girls(1)",
"CHORD NUMBER EIGHT(76)",
"CHRISTIAN DADA(35)",
"CHRISTINA ROHDE(59)",
"CHROME(1)",
"chronicle(17)",
"Chuggington(12)",
"chumchum(3250)",
"CHUMS(362)",
"Church's(14)",
"Ciaopanic(857)",
"CIAOPANIC TYPY(533)",
"CIBONE(541)",
"cielo blu(39)",
"CINOH(11)",
"CIPOLLA(25)",
"CISOLASSE(110)",
"CITRUS(62)",
"CIVILIZED(12)",
"CLANE(188)",
"Clarks(215)",
"Clarks Originals(3)",
"clasky(5)",
"CLASSIC(1)",
"CLASSY.(1)",
"CLATHAS(414)",
"CLAUDIA ROWE(5)",
"CLAUSTRUM(3)",
"Clef(113)",
"Clice de Paris(55)",
"CLOON KEEN ATELIER(1)",
"CLUCT(7)",
"CLUEL(1)",
"COACH(320)",
"COCA(144)",
"Cocoonist(463)",
"COCOSHNIK(752)",
"COCOSHNIK ONKITSCH(65)",
"COCUE(613)",
"COCURATA(2)",
"coen(2653)",
"COEUR(3)",
"COEUR D'OR(5)",
"COLE HAAN(197)",
"Coleman(425)",
"COLLAGE GALLARDAGALANTE(465)",
"COLLARS(17)",
"COLLECTHING THINGS(9)",
"collective circle by Johnbull(61)",
"Color(275)",
"COLORCTORS(130)",
"Columbia(1227)",
"Com2ons Code(17)",
"COMECHATTO&CLOSET(29)",
"comm. arch.(30)",
"COMME CA ISM(566)",
"Comme ca Mature(64)",
"COMME des GARCONS PARFUMS(17)",
"COMME des GARCONS POCKET(17)",
"COMMUNE DE PARIS(1)",
"C'omodo+plust(1)",
"con affetto(18)",
"con affetto(original)(152)",
"con affetto(select)(26)",
"CONCRETE DESIGN(9)",
"conges payes ADIEU TRISTESSE(246)",
"contego eyewear(42)",
"CONVERSE(953)",
"cooco(519)",
"Coohem(84)",
"COON(8)",
"Cooperstown Ball Cap(7)",
"CORALLO AZZURRO(33)",
"CORTES WORKS(64)",
"Cosme Kitchen(7)",
"COSMIC WONDER(196)",
"COSSHI(60)",
"Cote&Ciel(22)",
"COULEURVARIE(255)",
"COUP DE CHANCE(1221)",
"CRAP(36)",
"CRASH BAGGAGE(4)",
"CREA(1)",
"Cream Chantilly(2)",
"Creed(457)",
"CRESSY(2)",
"CRIMIE(18)",
"crocs(143)",
"crolla(2)",
"CROON A SONG(394)",
"crossing(2)",
"CROWN(1)",
"CRUCE anap(657)",
"CRYSTAL BALL(694)",
"Ctrl freak (10)",
"cuddle&kiss(211)",
"cuff(5)",
"Cul de Sac(47)",
"Culture Medium(253)",
"Culturhythm(7)",
"Current/Elliott(11)",
"CUSTOM CULTURE(389)",
"CUT(2)",
"CYDERHOUSE(1)"
]
