var list = [
"C by Chaos,-",
"C DIEM,カルペディエム",
"C&C California,シーアンドシーカリフォルニア",
"C&R,シーアンドアール",
"C.A.B.CLOTHING,キャブクロージング",
"C.ali,カリ",
"C.brumes,シーブリュームス",
"C.D.S BASIC,シーディーエスベーシック",
"C.E,シーイー",
"C.E.L.STORE,セルストア",
"C.F.P,",
"C.H.SUPPLY & CO，,シーエイチサプライ",
"C.I.L.,シーアイエル",
"C.L.N,シーエルエヌ",
"c.neeon,シーニーオン",
"C.P. COMPANY,",
"C.Pili,ピリ",
"c.r.a.f.t,クラフト",
"C.S.D,シーエスディー",
"C.T.plage,シーティー・プラージュ",
"C・C・†CROSS,シーシークロス",
"C1RCA,サーカ",
"C-44,",
"C6,シーシックス",
"ca$hmere,カシミア",
"CA4LA,カシラ",
"CA4LA loves Andy Warhol,カシラ ラヴズ アンディーウォーフォール",
"cabal,カバル",
"CABALLERO,キャバレロ",
"caban,キャバン",
"CABANE de ZUCCa,カバンドズッカ",
"CABBAGES & ROSES,キャベジズ アンド ローゼズ",
"Cabin Zero,キャビンゼロ",
"Cable,",
"CABLOCAMURIE　,カブロカムリエ",
"CABOOTS,カブーツ",
"CACHAREL,キャシャレル",
"cache cache,カシュ カシュ",
"Cachellie,カシェリエ",
"cachenez,カシュネ",
"CACTUS,カクタス",
"CACTUS DESIGN INC.,カクタスデザイン",
"Cactus..cepo.,カクタスセポ",
"Cafe du Cycliste,カフェドゥシクリスタ",
"Cafe.mag,カフェマグ",
"Cafeina,カフェイナ",
"CAFeNOIR,カフェノアール",
"Caffe,カフェ",
"CAGECITY,ケイジシティー",
"CAGE-LOW,ケージロウ",
"Cages,ゲージ",
"Caharel,-",
"Caie,カイエ",
"Cakeland,-",
"CAKES,ケイクス",
"Cal,カル",
"CAL O LINE,キャルオーライン",
"Calabrese,カラブレーゼ",
"calcium,カルシウム",
"CalCru,カルクルー",
"CALEE,キャリー",
"CALEIDOSCOPIO,カレイドスコピオ",
"CALI SURF,カリサーフ",
"calian,キャリアン",
"CALIBURN,カリバーン",
"calico,キャリコ",
"CALIFORNIA BRAND,カリフォルニアブランド",
"California Clothing Co.,",
"CALIFORNIA DREAMING,カリフォルニアドリーミング",
"CaLiFoRNia Vintage,カリフォルニアビンテージ",
"Calimar,カリマール",
"CALINER,カリネ",
"CALL&RESPONSE,コールアンドレスポンス",
"CALLA,カーラ",
"CALLAS,カラス",
"Callaway,キャロウェイ",
"Callipigia,カッリピージャ",
"callous,キャラス",
"CALMA,カルマ",
"Calman and Chelow,アマンアンドシーロー",
"calme,",
"Calms,カームス",
"Calvin Klein,カルバン・クライン",
"Calvin Klein Underwear,-",
"CALYPSO,カリプソ",
"Calzanor,カルザノール",
"CAMAIEU,カマイユ",
"CAMBER,キャンバー",
"CAMBIO,カンビオ",
"Cambridge Satchel, ",
"Cambridge Silversmiths,ケンブリッジシルバースミス",
"CAMCO,カムコ",
"Camelbak,キャメルバック",
"CAMEO,カメオ",
"CAMERON HAWAII,キャメロンハワイ",
"Cameron Racy,キャメロンレイシー",
"CAMERUCCI ARCHIVIO,カメルッチアルキビオ",
"CAMIERA,カミエラ",
"Camilla,カミーラ",
"CAMILLA AND MARC,カミラアンドマーク",
"Camilla Skovgaard,カミーラスコフガード",
"CAMILLE ENRICO,-",
"CAMILLE for LULU,カミーユフォールル",
"Camille Fournet,カミーユフォルネ",
"CAMINANDO,カミナンド",
"CAMO,カーモ",
"Camomilla,",
"Camouflage,カモウフレージ",
"Camouflage Kids,カモウフレージキッズ",
"Camp Service, ",
"campagne,カンパーニュ",
"CAMPER,カンペール",
"campion,",
"CAMPOMAGGI,カンポマッジ",
"Camui water massage,カムイウォーターマッサージ",
"CANADA GOOSE,カナダグース",
"Canadian Sweater Company Ltd.,カナディアンセーター",
"CANAL JEAN,キャナルジーン",
"CANAL STREET BIS,キャナルストリートビス",
"canal4℃,カナルヨンドシー",
"CANALI,カナーリ",
"CANAMO,カナーモ",
"CanCam,キャンキャン",
"candela,キャンデラ",
"CANDIES,キャンディーズ",
"Candle Studio MAGIERA,マギエラ",
"CANDLES & INCENSE, ",
"candlly,キャンドリー",
"CANDY,キャンディー",
"Candy Float,キャンディフロート",
"Candy Stripper,キャンディストリッパー",
"Canis Familiaris,カニスファミリアス",
"CANNABIS,カンナビス",
"CANNABIS LADIES,カンナビス レディース",
"CANOE,",
"Cantarelli,カンタレリ",
"Cantini&Cantini,カンティーニカンティーニ",
"Cantodea,-",
"CANTON,キャントン",
"cantwo,キャンツー",
"CANVAS.,キャンバス",
"Canyon de chelly,キャニオンデシェリー",
"CAP FAKE!!!,カップフェイク",
"capaf,カパフ",
"Cape HEIGHTS,ケープハイツ",
"Capelli,カペリ",
"Capelli of New York,-",
"capesmile,ケープスマイル",
"Capezio,カペジオ",
"caph,カーフ",
"CAPITAL HILL PRODUCT,キャピタルヒルプロダクト",
"CAPITAL RADIO ONE,キャピタルレディオワン",
"Capogiro Firenze,カポジーロ・フィレンツェ",
"CAPPELLETTI,カペレッティ",
"CAPPELLI,カペッリ",
"Cappelli Straworld,カペリストローワールド",
"CAPRGCORNUS,カプリコルナス",
"CAPRI GUANTI,カプリガンティ",
"CAPRICIEUX LE'MAGE,カプリシューレマージュ",
"CAPSEL,カプセル",
"CAPTAIN FIN,キャプテンフィン",
"Captains Helm,キャプテンズヘルム",
"CAPTURE,キャプチャー",
"caqu,サキュウ",
"CAR SHOE,カーシュー",
"Cara,-",
"Cara Couture NY,カーラクチュールニューヨーク",
"Caravana by A・I・C,キャラバーナ　バイ　エーアイシー",
"CARBALINE,カルバリン",
"CARBURETOR & CO,キャブレターアンドコー",
"CARDIGAN.,カーディガン",
"Care label,ケア レーベ",
"CAREER LINK,キャリアリンク",
"CARGO airtrans,カーゴエアートランス",
"Carhartt,カーハート",
"Carhartt WIP,カーハート ダブリューアイピー",
"CARIDEI,カリデイ",
"CARIN WESTER,キャリンウェスター",
"CARINE,カリネ",
"CARINER,",
"carino,カリーノ",
"Caristoga,",
"Carl Do Nas,-",
"Carletti,カレッティ",
"Carlie e felice,カーリーエフェリーチェ",
"carlife,カーライフ",
"carlife garden,",
"CARLO ROSSETTI,カルロロセッティ",
"CARLO VALENTINI,カルロバレンティーニ",
"Carlomagno,カロマグノ",
"CARLOS MIELE,カルロスミーレ",
"Carlota Joakina,カルロタジョアキナ",
"CARLY COLLECTION,",
"CARMEN CHAN,カーメンチャン",
"Carmen Salas,カルメンサラス",
"CARMINA,カルミナ",
"Carmine,カルミネ",
"carnelian,カーネリアン",
"carnet,カルネ",
"CARNET DE MODE,-",
"CARNET DE VOYAGE,カルネデボヤージュ",
"CARNIVAL,",
"CAROL CHRISTIAN POELL,キャロルクリスチャンポエル",
"Carol J.,キャロルジェイ",
"Carolina Bucci,キャロリーナ・ブッチ",
"CAROLINA GLASER,カロリナ グレイサー",
"Carolina glaser beaute,カロリナグレイサーボーテ",
"Carolina Glaser for men,カロリナグレイサーフォーメン",
"CAROLINA HERRERA,キャロライナヘレラ",
"CAROLINA K,カロライナケー",
"CAROLINE CHARLES,キャロラインチャールズ",
"CARON CALLAHAN,キャロンカラハン",
"CARRAIG DONN,キャレイグドン",
"CARRANO,カラーノ",
"Carre Royal,キャリーローヤル",
"CARREMENT BEAU,キャレマン　ボー",
"CARRERA,カレラ",
"Carried Away,-",
"Carrislabelle,-",
"CARRYNEST,キャリーネスト",
"CARTA,カルタ",
"Carter's,カーターズ",
"Cartier,カルティエ",
"Cartonnage,カルトナージュ",
"CARTRIDGE CASE,カートリッジ　ケース",
"CARTRIDGE CASE222,カートリッジケイス",
"Carvela,カーベラ",
"Carvela Comfort,カーヴェラコンフォート",
"Carvela Kurt Geiger,カーベラカートジェイガー",
"CARVEN,カルヴェン",
"Casa BRUTUS,カーサブルータス",
"casa do pe,カサドペ",
"CASADEI,カサディ",
"casanova,カザノヴァ",
"CASE SCENARIO,ケースシナリオ",
"Casely-Hayford,ケイスリーヘイフォード",
"CASEPLAY,ケースプレイ",
"CASEY VIDALENC,ケースリーヴィダレンク",
"CASH CA,カシュカ",
"CASHHIMI,カシミ",
"CASIO,カシオ",
"Caskal,-",
"CASPER JOHN,キャスパージョン",
"CASPER JOHN AIVER,キャスパージョンアイバー",
"CASPER JOHN SELECT,キャスパージョンセレクト",
"CASSANDERE,カサンドレ",
"CASSAVES,カザベス",
"Casselini,キャセリーニ",
"Casselini fifth avenue,キャセリーニフィフスアベニュー",
"CASSETTE,カセット",
"CASSETTEPLAYA,カセットプレイヤ",
"cassettepunch.,カセットパンチ",
"CASSEY GAN,キャッセイガン",
"CASSIDY'81,",
"C'ast vague,セベージュ",
"Castaner,カスタニェール",
"CASTANIER,カスタニエール",
"CASTANO,カスターノ",
"CASTELBAJAC,カステルバジャック",
"CASTELLARI,カステッラーリ",
"CASTELLER,カステリェール",
"CASUCA,",
"Cat Hammill,キャットハミル",
"Cat in the closet,キャットインザクローゼット",
"cat’s TSUMORI CHISATO,キャッツ　ツモリチサト",
"Catarisano,カタリザーノ",
"catene,カテネ",
"CATERINA BERTINI,カテリナベルティーニ",
"CATERINA LUCCHI,カテリーナルッキ",
"Cater-pillar,キャタピラー",
"Cath Kidston,キャスキッドソン",
"cathay,キャセイ",
"Catherine Harnel,キャサリンハーネル",
"CATHERINE MALANdRINO,キャサリンマランドリーノ",
"CATHERINE MICHIELS,キャサリンミッシェル",
"Catherine Parra ,キャサリンパーラー",
"cathy jane,キャシージェーン",
"Cathy's Concepts,キャシーズ コンセプツ",
"CATORCE,カトルセ",
"cat's,キャッツ",
"CAT'S PAW,キャッツポウ",
"cattle babysitter,キャトルベビーシッター",
"catworld,キャットワールド",
"CAUDALIE,-",
"CAUSE,コーズ",
"CAUSSE,コス",
"CAV-000,キャブゼロゼロゼロ",
"cava cava,サヴァサヴァ",
"Cavallini,カヴァリーニ",
"cavariA,キャバリア",
"CAYA,カヤ",
"CAYLER & SONS, ",
"CAZAL,カザール",
"CB by GARCIA,シービー　バイ　ガルシア",
"CBGB,シービージービー",
"CBOMB, ",
"CC SKYE,シーシースカイ",
"C-CLOSETPARK,シークローゼットパーク",
"C-COLLECTIVE,シーコレクティブ",
"CCP,",
"Ceanothus,セアノサス",
"CEASTERS,ケステル",
"CEBO,セボ",
"CEBOG,セボジー",
"cece,シーシー",
"cece.t,セセティー",
"Cecil Linc,セシルリンク",
"CECIL McBEE,セシルマクビー",
"CECILE BOCCARA,セシルボッカラ",
"Cecilia Gonzales,セシリアゴンザレス",
"CECILIA MA, ",
"cecilia prado,セシリアプラド",
"CEDRIC CHARLIER,セドリック シャルリエ",
"CEI,セイ",
"CELEC,セレク",
"CELESTE TESORIERO ,-",
"CelesteBlue ,セレステブルー",
"Celia Birtwell,セリア・バートウェル",
"CELINE,セリーヌ",
"CeLL,セル",
"Celt and Cobra,ケルトアンド　コブラ",
"Celtic Sheepskin,セルティック",
"CEMENT PRODUCE DESIGN,セメントプロデュースデザイン",
"Censored Sentient,センサード　センティエント",
"CENTINELA,センチネラ",
"Cento Felina,チェントフェリーナ",
"cepo,セポ",
"ceramika artystyczna,セラミカ　アルティスティッチナ",
"Ceramika Artystyzna,ツェラミカアルティスティチナ",
"CERASUS,ケラスス",
"CEROCHIO,セルッチオ",
"ceroLinea,セロリニア",
"CERRUTI,チェルッティ",
"CERUTTI,チェルッティ",
"Ces Puzzles,セ・パズル",
"Cesaire,セゼール",
"CESARE FABBRI,チェザレファブリ",
"Cesare Paciotti,チェザーレパチョッティ",
"CESARE PACIOTTI 4US,チョザレパチョッティフォーアス",
"CESKY MOFF,チェスキー　モフ",
"C'est pas grave,セパグラーブ",
"cha cha cha,",
"CHA CHA’S HOUSE OF ILL REPUTE,チャチャズ ハウス オブ イル リピュート",
"CHACH,チャチ",
"Chaco,チャコ",
"CHACO BAND,チャコバンド",
"CHAHAT,チャハット",
"Chain Reaction,-",
"CHAINGANG,チェインギャング",
"Chainloop,チェインループ",
"CHALAYAN,チャラヤン",
"CHaLK NYC,-",
"CHALLENGER,チャレンジャー",
"CHAMBER,チェンバー",
"Chambre,シャンブル",
"chambre de charme,シャンブルドゥシャーム",
"chambre de nimes,シャンブル ド ニーム",
"chamny,チャムニー",
"CHAMP MAGAZINE,チャンプ　マガジン",
"Champion,チャンピオン",
"CHAMULA,チャムラ",
"CHAN LUU,チャンルー",
"chancechance,チャンスチャンス",
"Chandelier,シャンデリエ",
]