var listg=[
"G-Star",
"Gabriele Colangelo",
"Gant by Michael Bastian",
"Gap",
"Gardem",
"Gareth Pugh",
"Gary Graham",
"Generra",
"Genny",
"Giamba",
"Giambattista Valli",
"Gianfranco Ferrè",
"Giles",
"Giles Deacon",
"Giorgio Armani",
"Giulietta",
"Givenchy",
"Graeme Armour",
"Graeme Black",
"Greg Lauren",
"Gregory Parkinson",
"Ground Zero",
"Gryphon",
"Gucci",
"Guy Laroche",
"G&F WORKERS(17)",
"G.KERO(1)",
"G.V.G.V.(151)",
"g;fifty(21)",
"GAIMO(145)",
"GALA Curios(1)",
"GALANCE(78)",
"galaxxxy(12)",
"GALERIE DES BAINS(1)",
"GALLARDAGALANTE(455)",
"GALLERIANT(177)",
"galopine&galopin(13)",
"GANRYU(48)",
"Garden of Eden(23)",
"GAS(259)",
"GASIUS(2)",
"GAVROUM(22)",
"GDC(387)",
"gelato pique(443)",
"gelato pique Baby＆Kids(3)",
"GELATO PIQUE HOMME(1)",
"Genri(109)",
"genten(348)",
"GEORGE FROST(2)",
"George's(1680)",
"GERRY(4)",
"get a life(4)",
"GIANNI CHIARINI(96)",
"GILBERT GILBERT(6)",
"GILD(76)",
"GINGER(1)",
"GINGER ALE(154)",
"GINZA(2)",
"GIORDANO(526)",
"GIORGIO BRATO(2)",
"giovanni(59)",
"giraffe(125)",
"GISELe(1)",
"GIZA(11)",
"glamb(11)",
"GLAMOROUS JANE(1)",
"GLEAN＆Co.(14)",
"Glen Prince(20)",
"GLENROYAL(64)",
"GLITGE(12)",
"GLITTER(1)",
"GLOBAL FORME CONCRETE(1069)",
"GLOBAL WORK(731)",
"GLOBE(6)",
"glory crew(6)",
"Gloverall(14)",
"GLOW(1)",
"go slow caravan(419)",
"goa(583)",
"GOHEMP(698)",
"Gola(23)",
"GOLDEN GOOSE(41)",
"Gome 56(20)",
"gomme(392)",
"gonoturn(84)",
"goocy(279)",
"GOOD BREATH EQUIPMENT & CO.(25)",
"good hYOUman(1)",
"Good On(8)",
"Goodwear(5)",
"Goody Grams(39)",
"Goody Grams Add(52)",
"Gorilland(18)",
"GOSH(31)",
"GOSSIPS(2)",
"GOTTEX(1)",
"GOUT COMMUN(558)",
"GOWEST(44)",
"GRACE by GOODY GRAMS(108)",
"GRACE CONTINENTAL(961)",
"gracious lapin(77)",
"Gramicci(33)",
"GRANDEUR PLUS(2)",
"GRANDMA MAMA DAUGHTER(8)",
"graniph(726)",
"Granite Gear(9)",
"granpapa(248)",
"grapevine by k3(68)",
"GRAPHT(44)",
"GRAVIS(78)",
"GRAY MAGIC(529)",
"Gready Brilliant(254)",
"GREAT BARRIER ISLAND BEE(14)",
"GREED International(45)",
"green label relaxing(1734)",
"Green Parks(727)",
"GREEN PEANUTS(10)",
"GREENDALE GARNET(81)",
"GREGORY(389)",
"GROCERIES(3)",
"grove(2753)",
"G-SHOCK(30)",
"GSI(29)",
"G-STAR RAW(160)",
"gtm(3)",
"GUACAMOLE(412)",
"GUCCI(8)",
"GUELL MUSTARD(2)",
"Guess(166)",
"GUILD PRIME(392)",
"GUILLAUMOND(4)",
"GUIONNET(9)",
"Gula(4)",
"gunda(20)",
"GUNG HO(16)",
"GYDA(331)",
"gym master(686)",
"GYMPHLEX(35)",
"GYPSY CLOTH(111)",
"Gypsy Fire Stream(2)",
"GYPSY THREE ORCHESTRA(65)",
]
