var listr = [
"RAD by Rad Hourani",
"Rachel Antonoff",
"Rachel Comey",
"Rachel Roy",
"Rachel Zoe",
"Rad Hourani",
"Rafael Cennamo",
"Rag & Bone",
"Raleigh",
"Ralph & Russo",
"Ralph Lauren",
"Ralph Rucci",
"Raquel Allegra",
"Rebecca Minkoff",
"Rebecca Taylor",
"Red Valentino",
"Reed Krakoff",
"Reem Acra",
"Requiem",
"Revillon",
"Richard Chai",
"Richard Chai Love",
"Richard Nicoll",
"Rick Owens",
"Rivini",
"Robert Rodriguez",
"Roberto Cavalli",
"Rochas",
"Rock & Republic",
"Rodarte",
"Rodebjer",
"Rodnik",
"Roksanda Ilincic",
"Roland Mouret",
"Romona Keveza",
"Rosie Assoulin",
"Rue du Mail",
"Ruffian",
"Ryan Lo",
"Réyes",
"rhie",
"rosetta getty",
"ryan roche",
"",
"",
"R&E(258)",
"RACAL(24)",
"radiance de SYHSE(20)",
"RADIO EVA(69)",
"RADLEY(125)",
"RAEN(2)",
"RAF SIMONS(3)",
"rag & bone(186)",
"rag&bone/JEAN(6)",
"RAGEBLUE(287)",
"RagsUnite(149)",
"RANDA(775)",
"RANDOM(18)",
"rapiecage(233)",
"RATTLE TRAP(26)",
"Ravijour(705)",
"Ray(1)",
"Ray BEAMS(2186)",
"Ray Cassin(1172)",
"Ray-Ban(12)",
"rdv o glove(21)",
"REAL ACTION HEROES(5)",
"REBECCA TAYLOR(167)",
"REBECCAMINKOFF(6)",
"RebeL(5)",
"Recreation journal standard L’essage(1)",
"Recreational Vehicle(92)",
"RED CHOP WORKS(7)",
"RED Profile(49)",
"Reebok(425)",
"REEF(4)",
"Reene(47)",
"Reflect(1136)",
"Regalect(163)",
"rehacer(363)",
"Reign(3)",
"Reir(147)",
"REKISAMI(27)",
"relacher(178)",
"Relate(633)",
"REMI RELIEF(64)",
"remi&reid(12)",
"REN(457)",
"Rene Gurskov(1)",
"REPEL(48)",
"repetto(120)",
"REPLAY(161)",
"Reproduction@ｉ(26)",
"RES DENIM(3)",
"Resexxy(484)",
"RESTERODS(7)",
"retaW(84)",
"REVE D'UN JOUR(40)",
"Revelations/(6)",
"revionnet(4)",
"Rew de Rew(944)",
"REZOY(208)",
"RHRB(5)",
"Ribbon hakka kid's(24)",
"Riberce(117)",
"rich(172)",
"Rick Owens(2)",
"RICO GOLD(35)",
"Rie Miller(3)",
"rienda(726)",
"Right-on(407)",
"RiiiKa(133)",
"rikolekt(7)",
"Rin clover(96)",
"Rinajour(873)",
"RINASCIMENTO(29)",
"RiNc (464)",
"Rirandture(192)",
"Risa Magli(411)",
"RITA JEANS TOKYO(174)",
"Rivieras(9)",
"RLIGHTs(18)",
"RNA(1122)",
"RNA SWEAT(348)",
"RNA-N(957)",
"ROBE(21)",
"ROBERTO　BOTELLA(3)",
"ROBERTO COLLINA(25)",
"Robin Rose(21)",
"robita(153)",
"Rock Spring(28)",
"ROCKMOUNT(4)",
"ROCKPORT(77)",
"Rocky Mountain FeatherBed(6)",
"RODE SKO(340)",
"Rodeo Crowns(2)",
"RODEO CROWNS WIDE BOWL(840)",
"ROEN(60)",
"Roen Produced by HIROMUTAKAHARA(2)",
"roial(532)",
"ROLA(1)",
"rooms(24)",
"ROOTOTE(449)",
"ROPE'(690)",
"ROPE' mademoiselle(507)",
"ROPE' PICNIC(1706)",
"rosa mosa(4)",
"Rosarymoon(83)",
"ROSE BUD(2959)",
"ROSE BUD COUPLES (2250)",
"ROSE DE MARRAKECH(6)",
"ROSEanna(12)",
"RoseMarie seoir(38)",
"ROSIEE(62)",
"ROSSO(628)",
"ROSTER SOX(11)",
"ROTAR(120)",
"ROTTWEILER(24)",
"Rouge vif(976)",
"rougeloup(268)",
"ROXY(1363)",
"ROYAL PARTY(558)",
"RPKO(10)",
"Rubb(17)",
"RUBBER DUCK(11)",
"RUBBER KILLER(46)",
"Rubyrivet(443)",
"RUCOLINE(130)",
"RUGGED FACTORY(265)",
"rukkilill(150)",
"RUMBLE RED(7)",
"russet(591)",
"RVCA(15)",
"rxmance(25)",
]