var listd =[
"DKNY",
"Daks",
"Daks by Giles Deacon",
"Damir Doma",
"Danielle Scutt",
"Daryl K",
"Daughters by Obedient Sons",
"David Koma",
"Davidelfin",
"Dean Quinn",
"Delpozo",
"Dennis Basso",
"Derek Lam",
"Derercuny",
"Devi Kroell",
"Diane von Furstenberg",
"Diesel Black Gold",
"Dion Lee",
"Dior",
"Dolce&Gabbana",
"Dondup",
"Donna Karan",
"Doo.Ri",
"Douglas Hannant",
"Dries Van Noten",
"Dsquared2",
"Dsquared²",
"Duckie Brown",
"Duro Olowu",
"",
"D.M.G.(33)",
"daboro(49)",
"dada flora(5)",
"DAILY NEWS(6)",
"DAL(29)",
"DAMMY(170)",
"DA-NA Vie(5)",
"DandA by danny&anne(80)",
"Daniel Wellington(50)",
"Danke(6)",
"Danner(2)",
"Danny&Anne(162)",
"DARKSHINY(15)",
"dazzlin(518)",
"D-BROS(149)",
"DC SHOES(240)",
"Dea Kudibal(8)",
"Dear Princess(206)",
"Debbie Regina(2)",
"Debut de Fiore(14)",
"DECADE(160)",
"Dedes(111)",
"Deepa Gurnani(20)",
"Defilious(80)",
"deicy(323)",
"DELUXE(57)",
"Demi-Luxe BEAMS(1286)",
"DEMYLEE(58)",
"DENIM & SUPPLY(182)",
"Denime(309)",
"DENIS(3)",
"Departure2(3)",
"DEREK LAM(6)",
"DESCENTE(156)",
"Desert　Rose(87)",
"DESSERTS(1)",
"Dessin UNTITLED(820)",
"Detail(4)",
"DETAILS(646)",
"Deuxieme Classe(317)",
"devadurga(18)",
"DEVASTEE(81)",
"Devinette(1014)",
"DI CLASSE(7)",
"Dickies(564)",
"dictionary(1)",
"didizizi(135)",
"DIESEL(915)",
"Dieu(15)",
"dimorphotheca(4)",
"Dior homme(1)",
"dip(38)",
"Discoat(12)",
"Discoat Parisien MENS(7)",
"Discoat Parisien WOMENS(595)",
"DISCOVERED(2)",
"DISCUS(40)",
"DISSIZIT!(1)",
"Dｉｖｅｒｓｈｉｏｎ(4)",
"do organic(7)",
"DOARAT(46)",
"DOLLY GIRL BY ANNA SUI(404)",
"Dolly&Molly(333)",
"DOMA(7)",
"domani(5)",
"DOMENICO+SAVIO(32)",
"Dorothy Lang(4)",
"Dorry Doll(184)",
"Dot＆Stripes CHILD WOMAN(192)",
"DOUBLE FOOT WEAR(2)",
"DOUBLE NAME(383)",
"DOUBLE STANDARD CLOTHING(617)",
"DOUBLE STEAL(63)",
"DOUBTFUL AS DOUBLE(R)(64)",
"DouDou(409)",
"Doudou et Compagnie(2)",
"Doux archives(388)",
"DouxToucher(8)",
"DOWBL(31)",
"Dr Denim(3)",
"Dr.Martens(49)",
"DRAGON BEARD(41)",
"Dress up everyday(161)",
"DRESSCAMP(194)",
"DRESSEDUNDRESSED(21)",
"DRESSLAVE(618)",
"DRESSTERIOR(567)",
"Drifter(236)",
"DRitte(2)",
"Droite lautreamont(192)",
"Drowse and yet...(10)",
"DRWCYS(499)",
"DSQUARED2(237)",
"Dubeige(36)",
"DUCK AND COVER(7)",
"DUL DE VERRE(38)",
"Dulcamara(29)",
"Duller(1)",
"d'un a dix(145)",
"DUPE(5)",
"DUPPIES(86)",
"Durare(55)",
"DURAS(708)",
"DURAS ambient(366)",
"durbuy(25)",
"DUVETICA(81)",
"DYNAMO(1)",
"Dyson(10)",
]