var listv = [
"VFiles",
"VPL",
"Valentin Yudashkin",
"Valentino",
"Vanessa Bruno",
"Vanessa Seward",
"Vena Cava",
"Vera Wang",
"Vera Wang Lavender Label",
"Veronica Beard",
"Veronique Branquinho",
"Verrier",
"Versace",
"Versus",
"Victor Alfaro",
"Victor De Souza",
"Victoria Beckham",
"Victoria Victoria Beckham",
"Vika Gazinskaya",
"Viktor & Rolf",
"Vionnet",
"Visvim",
"Vivienne Tam",
"Vivienne Westwood",
"Vivienne Westwood Red Label",
"Véronique Leroy",
"vetements",
"",
"V SEVEN TWELVE THIRTY(124)",
"v::room(14)",
"VA VENDOME AOYAMA(199)",
"VALLEY HIGH(9)",
"vanessabruno(210)",
"vanitybeauty(232)",
"VANQUISH(78)",
"VANS(814)",
"VANS VAULT(6)",
"Vantique(8)",
"Varde77(6)",
"Vargas(2)",
"VARISISTA(4)",
"VASIC New York(2)",
"VCTO(1)",
"Velnica(29)",
"Velvet Lounge(204)",
"VENCEEXCHANGE(801)",
"VENDOME AOYAMA(389)",
"VENDOME BOUTIQUE(117)",
"VERBENAS(16)",
"VERSUS(14)",
"VERY(1)",
"Verybrain(1)",
"Vestal(12)",
"Via Demizon(69)",
"VIA DEMIZON DOUX(5)",
"Viaggio Blu(269)",
"VIBGYOR(430)",
"VIBGYOR Women(735)",
"VICKY(300)",
"VICTIM(1)",
"VICTORIA(20)",
"VIDA＋(8)",
"VIE(4)",
"vihere(10)",
"vikka(1)",
"VIKTOR&ROLF(5)",
"Village Vanguard(48)",
"VINCA(20)",
"vingtrois(129)",
"Vinyl(1)",
"VINYL COLLECTIBLE DOLLS(7)",
"VIOLA(3)",
"Virca(187)",
"VIRGO(11)",
"ViS(1500)",
"VISION STREET WEAR(37)",
"Vita-Mix(4)",
"VIVAYOU(153)",
"ViVi(1)",
"ViVi fleurs(11)",
"Vivienne Westwood(135)",
"VIVIFY(419)",
"Vlas Blomme(75)",
"Vogli(1)",
"VOGUE girl(1)",
"VOGUISH(8)",
"VOLCOM(1568)",
"VONZIPPER(4)",
"VOTE MAKE NEW CLOTHES(2)",
"VOTIVO(2)",
"VT(203)",
"VTOPIA(73)",
]