var listj = [
"J Brand",
"J. JS.LEE",
"J. Mendel",
"J.Crew",
"J.Mendel",
"J.W. Anderson",
"JI OH",
"Jacquemus",
"Jaeger London",
"James Long",
"Jasmin Shokrian",
"Jasmine Di Milo",
"Jason Wu",
"Jay Ahr",
"Jean Charles de Castelbajac",
"Jean Paul Gaultier",
"Jean-Paul Lespagnard",
"Jean-Pierre Braganza",
"Jeffrey Chow",
"Jen Kao",
"Jenni Kayne",
"Jenny Packham",
"Jens Laugesen",
"Jeremy Laing",
"Jeremy Scott",
"Jil Sander",
"Jil Sander Navy",
"Jill Stuart",
"John Galliano",
"John Rocha",
"Joie",
"Jonathan Saunders",
"Jonathan Simkhai",
"Joseph",
"Josephus Thimister",
"Josh Goot",
"Josie Natori",
"Jovovich-Hawk",
"Juan Carlos Obando",
"Juicy Couture",
"Julian Louie",
"Julien David",
"Julien Macdonald",
"Junya Watanabe",
"Just Cavalli",
"",
"J&Goodmanhouse(7)",
"J&M Davidson(128)",
"J.FERRY(116)",
"J.O.T.T(1)",
"J.PRESS(1074)",
"J.PRESS YORK STREET(260)",
"J.R.Watkins(41)",
"JACK SPADE(1)",
"JACKSON MATISSE(34)",
"JAM HOME MADE(367)",
"JAMA RICO(41)",
"JAMES PERSE(2)",
"Jamgarden(2)",
"Jamin Puech(6)",
"JANE SMITH / JOHN SMITH(48)",
"JANSPORT(239)",
"J'attache organic(66)",
"JAyco(10)",
"Jean genie & hungry freaks, daddy(1)",
"JEAN GRISONI POUR VENDOME AOYAMA(15)",
"JEAN NASSAUS(29)",
"JEANASIS(362)",
"Jeffrey Campbell(193)",
"JELLY(1)",
"JELLY BEANS(455)",
"JENEVIEVE(109)",
"JET(512)",
"JETSET SOLO PLUS (545)",
"JEWEL(8)",
"Jewel Changes(975)",
"Jewelna Rose(709)",
"Jieda(30)",
"JiJi travail(15)",
"JILL by JILLSTUART(458)",
"JILLSTUART(489)",
"JIMMY CHOO(3)",
"Jines(1098)",
"JOE PORTER(42)",
"Joelle Gagnard(234)",
"JOEY FACTORY(4)",
"JOHN LAWRENCE SULLIVAN(30)",
"JOHN SMEDLEY(70)",
"JOHN&PEARL(1)",
"Johnbull Private labo(160)",
"JOHNNY MOKE(6)",
"Johnsotons of Elgin(6)",
"JohnUNDERCOVER(4)",
"JOLI(7)",
"Jonnlynx(6)",
"JOOMI LIM(2)",
"JORDAN BRAND(8)",
"JOSEPH(212)",
"Josie by Natori(4)",
"Jouete(1732)",
"jouetie(1224)",
"JOUR de Language(125)",
"JOURNAL STANDARD(1336)",
"journal standard Furniture (394)",
"JOURNAL STANDARD J.S HOMESTEAD(34)",
"journal standard L'essage(402)",
"JOURNAL STANDARD LUXE(293)",
"JOURNAL STANDARD relume(830)",
"Journal Standard TRISECT(20)",
"JOYRICH(339)",
"JUCO.(6)",
"JULIEN DAVID(18)",
"JUN WATANABE(15)",
"JUNCO Paris(2)",
"Juniper Ridge(6)",
"JUNK FOOD(7)",
"JUNK STORE(15)",
"JUNRed(76)",
"JUPITER(344)",
"JURIANO JURRIE(332)",
"JUSGLITTY(341)",
"JUUN.J(1)",
"Juze(54)",
]